/**
 * Permission Dictionary (Source of Truth)
 * Based on BA Document: 2.1. PHÂN RÃ & CHUẨN HÓA QUYỀN phase 1.md
 * Format: RESOURCE.ACTION
 */

export const PERMISSIONS = {
    // Platform Level (SYS_ADMIN)
    PLATFORM_ORG_CREATE: 'PLATFORM_ORG.CREATE',
    PLATFORM_ORG_READ: 'PLATFORM_ORG.READ',
    PLATFORM_ORG_UPDATE: 'PLATFORM_ORG.UPDATE',
    PLATFORM_ORG_APPROVE: 'PLATFORM_ORG.APPROVE',
    PLATFORM_ORG_SUSPEND: 'PLATFORM_ORG.UPDATE', // BA US-SYS-01-02
    PLATFORM_ORG_RESTORE: 'PLATFORM_ORG.RESTORE',
    PLATFORM_ORG_DESTROY: 'PLATFORM_ORG.DESTROY',
    SYS_AUDIT_READ: 'SYS_AUDIT.READ',
    SESSION_IMPERSONATE: 'SESSION.IMPERSONATE',

    // Tenant Level (ORG_ADMIN, CEO)
    TENANT_ORG_READ: 'TENANT_ORG.READ',
    TENANT_ORG_UPDATE: 'TENANT_ORG.UPDATE',
    ORG_USER_CREATE: 'ORG_USER.CREATE',
    ORG_USER_READ: 'ORG_USER.READ',
    ORG_USER_UPDATE: 'ORG_USER.UPDATE',
    ORG_USER_DELETE: 'ORG_USER.DELETE',
    ORG_USER_RESTORE: 'ORG_USER.RESTORE',
    ORG_USER_DESTROY: 'ORG_USER.DESTROY',
    ORG_USER_INVITE: 'ORG_USER.INVITE',
    ORG_USER_RESET_PASS: 'ORG_USER.UPDATE', // US-ORG-01-05

    ROLE_PERM_CREATE: 'ROLE_PERM.CREATE',
    ROLE_PERM_READ: 'ROLE_PERM.READ',
    ROLE_PERM_UPDATE: 'ROLE_PERM.UPDATE',
    ROLE_PERM_DELETE: 'ROLE_PERM.DELETE',

    LOOKUP_ALL: 'LOOKUP.ALL', // Project tags, statuses, etc.
    ACTIVITY_READ: 'ACTIVITY.READ',

    RECYCLE_BIN_READ: 'RECYCLE_BIN.READ',
    RECYCLE_BIN_RESTORE: 'RECYCLE_BIN.RESTORE',
    RECYCLE_BIN_DESTROY: 'RECYCLE_BIN.DESTROY',

    // Project & Task (PM, EMP)
    PROJECT_CREATE: 'PROJECT.CREATE',
    PROJECT_READ: 'PROJECT.READ',
    PROJECT_UPDATE: 'PROJECT.UPDATE',
    PROJECT_DELETE: 'PROJECT.DELETE',
    PROJECT_RESTORE: 'PROJECT.RESTORE',
    PROJECT_EXPORT: 'PROJECT.EXPORT',
    PROJECT_IMPORT: 'PROJECT.IMPORT',

    PRJ_LOCK_LOCK: 'PRJ_LOCK.LOCK',
    PRJ_LOCK_UNLOCK: 'PRJ_LOCK.UNLOCK',
    PRJ_NOTIF_CFG_READ: 'PRJ_NOTIF_CFG.READ',
    PRJ_NOTIF_CFG_UPDATE: 'PRJ_NOTIF_CFG.UPDATE',

    TASK_CREATE: 'TASK.CREATE',
    TASK_READ: 'TASK.READ',
    TASK_UPDATE: 'TASK.UPDATE',
    TASK_DELETE: 'TASK.DELETE',
    TASK_ASSIGN: 'TASK.ASSIGN',
    TASK_IMPORT: 'TASK.IMPORT',
    TASK_EXPORT: 'TASK.EXPORT',

    SUBTASK_CREATE: 'SUBTASK.CREATE',
    SUBTASK_READ: 'SUBTASK.READ',
    SUBTASK_UPDATE: 'SUBTASK.UPDATE',
    SUBTASK_DELETE: 'SUBTASK.DELETE',

    TIME_LOG_LOG: 'TIME_LOG.LOG_TIME',
    TIME_LOG_READ: 'TIME_LOG.READ',
    TIME_LOG_UPDATE: 'TIME_LOG.UPDATE',
    TIME_LOG_DELETE: 'TIME_LOG.DELETE',

    TAG_READ: 'TAG.READ',
    TAG_UPDATE: 'TAG.UPDATE',

    COMMENT_CREATE: 'COMMENT.CREATE',
    COMMENT_READ: 'COMMENT.READ',

    CUSTOM_FIELD_CREATE: 'CUSTOM_FIELD.CREATE',
    CUSTOM_FIELD_UPDATE: 'CUSTOM_FIELD.UPDATE',

    ASSET_CREATE: 'ASSET.CREATE',
    ASSET_READ: 'ASSET.READ',
    ASSET_DOWNLOAD: 'ASSET.DOWNLOAD',
    ASSET_DELETE: 'ASSET.DELETE',

    RESOURCE_CREATE: 'RESOURCE.CREATE',
    RESOURCE_READ: 'RESOURCE.READ',
    RESOURCE_UPDATE: 'RESOURCE.UPDATE',
    RESOURCE_SHARE: 'RESOURCE.SHARE',

    // HR & Finance (CEO, PM with permission)
    COMPENSATION_READ: 'COMPENSATION.READ',
    COMPENSATION_UPDATE: 'COMPENSATION.UPDATE',
    JOB_CONTRACT_READ: 'JOB_CONTRACT.READ',
    JOB_CONTRACT_UPDATE: 'JOB_CONTRACT.UPDATE',

    // Reporting
    REPORT_CREATE: 'REPORT.CREATE',
    REPORT_SUBMIT: 'REPORT.SUBMIT',
    REPORT_READ: 'REPORT.READ',
    REPORT_APPROVE: 'REPORT.APPROVE',
    REPORT_EXPORT: 'REPORT.EXPORT',
    REACTION_REACTION: 'REACTION.REACTION',

    // Personal & Notifications
    MY_TASK_ALL: 'MY_TASK.ALL',
    DASHBOARD_READ: 'DASHBOARD.READ',
    NOTIFICATION_READ: 'NOTIFICATION.READ',
    NOTIFICATION_UPDATE: 'NOTIFICATION.UPDATE',
} as const;

/**
 * Role Presets for Frontend Mocking
 * Defined in BA sections 5.1 to 5.5
 */
export const ROLE_PERMISSIONS = {
    SYS_ADMIN: [
        // US-SYS-00: Session
        PERMISSIONS.PLATFORM_ORG_CREATE,
        PERMISSIONS.PLATFORM_ORG_READ,
        PERMISSIONS.PLATFORM_ORG_UPDATE,
        PERMISSIONS.PLATFORM_ORG_APPROVE,
        PERMISSIONS.PLATFORM_ORG_RESTORE,
        PERMISSIONS.PLATFORM_ORG_DESTROY,
        PERMISSIONS.ORG_USER_CREATE,
        PERMISSIONS.ORG_USER_UPDATE,
        PERMISSIONS.ROLE_PERM_CREATE,
        PERMISSIONS.ROLE_PERM_READ,
        PERMISSIONS.ROLE_PERM_UPDATE,
        PERMISSIONS.ROLE_PERM_DELETE,
        PERMISSIONS.SESSION_IMPERSONATE,
        PERMISSIONS.SYS_AUDIT_READ,
        PERMISSIONS.PROJECT_CREATE,
    ],
    ORG_ADMIN: [
        // US-ORG-00: Session
        PERMISSIONS.ORG_USER_CREATE,
        PERMISSIONS.ORG_USER_INVITE,
        PERMISSIONS.ORG_USER_READ,
        PERMISSIONS.ORG_USER_UPDATE,
        PERMISSIONS.ORG_USER_DELETE,
        PERMISSIONS.ORG_USER_RESTORE,
        PERMISSIONS.ROLE_PERM_READ,
        PERMISSIONS.ROLE_PERM_UPDATE,
        PERMISSIONS.TENANT_ORG_UPDATE,
        PERMISSIONS.LOOKUP_ALL,
        PERMISSIONS.RECYCLE_BIN_READ,
        PERMISSIONS.RECYCLE_BIN_RESTORE,
        PERMISSIONS.RECYCLE_BIN_DESTROY,
        PERMISSIONS.SYS_AUDIT_READ,
        PERMISSIONS.DASHBOARD_READ,
        PERMISSIONS.PROJECT_CREATE,
    ],
    CEO: [
        // US-CEO-00: Session
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.ORG_USER_READ,
        PERMISSIONS.JOB_CONTRACT_READ,
        PERMISSIONS.COMPENSATION_READ,
        PERMISSIONS.REPORT_READ,
        PERMISSIONS.REPORT_APPROVE,
        PERMISSIONS.REACTION_REACTION,
        PERMISSIONS.COMMENT_CREATE,
        PERMISSIONS.ACTIVITY_READ,
        PERMISSIONS.NOTIFICATION_READ,
        PERMISSIONS.RECYCLE_BIN_READ,
        PERMISSIONS.MY_TASK_ALL,
        PERMISSIONS.DASHBOARD_READ,
        PERMISSIONS.PROJECT_CREATE,
    ],
    PROJECT_MANAGER: [
        // US-MNG-00: Session
        PERMISSIONS.PROJECT_CREATE,
        PERMISSIONS.PROJECT_READ,
        PERMISSIONS.PROJECT_UPDATE,
        PERMISSIONS.TASK_CREATE,
        PERMISSIONS.TASK_READ,
        PERMISSIONS.TASK_UPDATE,
        PERMISSIONS.TASK_DELETE,
        PERMISSIONS.TASK_ASSIGN,
        PERMISSIONS.TASK_IMPORT,
        PERMISSIONS.TASK_EXPORT,
        PERMISSIONS.SUBTASK_READ,
        PERMISSIONS.TAG_READ,
        PERMISSIONS.TAG_UPDATE,
        PERMISSIONS.ASSET_CREATE,
        PERMISSIONS.ASSET_READ,
        PERMISSIONS.ASSET_DOWNLOAD,
        PERMISSIONS.COMMENT_CREATE,
        PERMISSIONS.COMMENT_READ,
        PERMISSIONS.CUSTOM_FIELD_CREATE,
        PERMISSIONS.CUSTOM_FIELD_UPDATE,
        PERMISSIONS.PRJ_LOCK_LOCK,
        PERMISSIONS.PRJ_LOCK_UNLOCK,
        PERMISSIONS.ORG_USER_READ,
        PERMISSIONS.COMPENSATION_READ,
        PERMISSIONS.RESOURCE_CREATE,
        PERMISSIONS.RESOURCE_READ,
        PERMISSIONS.RESOURCE_UPDATE,
        PERMISSIONS.RESOURCE_SHARE,
        PERMISSIONS.ACTIVITY_READ,
        PERMISSIONS.PRJ_NOTIF_CFG_READ,
        PERMISSIONS.PRJ_NOTIF_CFG_UPDATE,
        PERMISSIONS.RECYCLE_BIN_READ,
        PERMISSIONS.RECYCLE_BIN_RESTORE,
        PERMISSIONS.RECYCLE_BIN_DESTROY,
        PERMISSIONS.MY_TASK_ALL,
        PERMISSIONS.REPORT_READ,
    ],
    EMPLOYEE: [
        // US-EMP-00: Session
        PERMISSIONS.TASK_READ,
        PERMISSIONS.TASK_UPDATE, // Controlled by Field-level (Optimistic Locking)
        PERMISSIONS.SUBTASK_CREATE,
        PERMISSIONS.SUBTASK_READ,
        PERMISSIONS.SUBTASK_UPDATE,
        PERMISSIONS.SUBTASK_DELETE,
        PERMISSIONS.ASSET_CREATE,
        PERMISSIONS.ASSET_DOWNLOAD,
        PERMISSIONS.COMMENT_CREATE,
        PERMISSIONS.COMMENT_READ,
        PERMISSIONS.TIME_LOG_LOG,
        PERMISSIONS.TIME_LOG_READ,
        PERMISSIONS.TIME_LOG_UPDATE,
        PERMISSIONS.TIME_LOG_DELETE,
        PERMISSIONS.REPORT_CREATE,
        PERMISSIONS.REPORT_SUBMIT,
        PERMISSIONS.REPORT_READ,
        PERMISSIONS.REPORT_EXPORT,
        PERMISSIONS.ACTIVITY_READ, // Own only (handled by backend)
        PERMISSIONS.NOTIFICATION_READ,
        PERMISSIONS.NOTIFICATION_UPDATE,
        PERMISSIONS.RECYCLE_BIN_READ,
        PERMISSIONS.RECYCLE_BIN_RESTORE,
        PERMISSIONS.MY_TASK_ALL,
    ]
};

export type AppPermission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export type AppRole = keyof typeof ROLE_PERMISSIONS;
